type BingoRefType = Record<'selectRandomNumber', () => number>;

type GameRoomStyles = Record<
    'game-header'
    | 'game-header-prefix'
    | 'player-info-list-item'
    | 'player-info-list-item-winner'
    | 'player-info-list-item-container'
    | 'player-info-list-item-container-winner'
    | 'winner-crown'
    | 'player-info-list-container'
    | 'left-panel-main'
    | 'glass-card'
    | 'chat-input-container'
    | 'chat-input'
    | 'chat-preview-card'
    | 'chat-preview-header'
    | 'chat-expand-button'
    | 'chat-preview-list'
    | 'chat-preview-item'
    | 'chat-preview-name'
    | 'chat-popup-list'
    | 'chat-popup-item'
    | 'chat-popup-item-own'
    | 'chat-popup-name'
    | 'chat-popup-message'
    | 'chat-empty-text'
    | 'chat-empty-text-popup'
    | 'postgame-fade'
    | 'leaderboard-panel'
    | 'leaderboard-enter'
    | 'leaderboard-title'
    | 'leaderboard-list'
    | 'leaderboard-item'
    | 'leaderboard-item-winner'
    | 'leaderboard-rank'
    | 'leaderboard-name'
    | 'leaderboard-name-winner'
    | 'leaderboard-winner-crown'
    | 'leaderboard-score'
    | 'leaderboard-badge'
    | 'postgame-chat-panel'
    | 'postgame-chat-title'
    | 'postgame-chat-list'
    | 'leaderboard-stage'
    | 'chat-shell'
    | 'chat-shell-collapsed'
    | 'chat-shell-expanded'
    | 'chat-shell-header'
    | 'chat-shell-history'
    | 'chat-shell-input'
    | 'chat-emoji-picker'
    | 'chat-emoji-item'
    | 'chat-emoji-preview'
    | 'chat-inline-emoji'
    | 'chat-inline-emoji-asset'
    | 'chat-popup-item-sticker'
    | 'chat-popup-message-sticker'
    | 'chat-sticker-emoji'
    | 'chat-sticker-emoji-asset'
    | 'leaderboard-panel-right'
    | 'leaderboard-actions'
    | 'replay-button'
    , string
>

declare module "*/GameRoom.module.css" {
    const content: GameRoomStyles;
    export default content;
}